[entryPoints]
    [entryPoints.http]
     address = ":8080"

[providers]
[providers.file]
[http]
    [http.routers]
       [http.routers.auth-router]
          rule = "Path(`/auth`)"
          service = "auth"
          entryPoints = ["http"]

    [http.services]
          [http.services.auth.loadbalancer]
            [[http.services.auth.loadbalancer.servers]]
              url = "http://myhost.com:8080/auth"